### ISSUE TITLE
[REQ] Component Request: BME688

### ISSUE THREAD

**Issue by ctgreybeard** [adafruit/Wippersnapper_Components#64]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit BME688

**What type of component is this (i.e.: Pin, I2C)?**
I2C Temperature, Humidity, Pressure and Gas Sensor - STEMMA QT

**Product URL or Datasheet**
[BME688](https://www.adafruit.com/product/5046)

**Additional context**
The current BME680 definition fails when using the BME688. I am going to take a stab at creating this definition but I did want to get my request on record.

**Comment by brentru** [comment]
This issue is marked for [Hacktoberfest 2022](https://hacktoberfest.com/). If you are participating in Hacktoberfest and want to take on this issue, please first **fully read through** the guide for ["How to add a new component to Adafruit IO WipperSnapper"](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper).

For I2C Components to work, please note that you are required to add **both** an I2C component definition ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)) to this repository **and** an I2C component driver ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)) to [the WipperSnapper Firmware Repository](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/).

If you have any questions, comments, or concerns, please feel free to tag me in the comments here, or in your pull request for review. 

Happy Hackin'!
