### ISSUE TITLE
eTape Liquid Level Sensor

### ISSUE THREAD

**Issue by tylerdcooper** [adafruit/Wippersnapper_Components#7]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
eTape Liquid Level Sensor (any length or style)

**Product URL or Datasheet**
https://www.adafruit.com/product/3828

There are a few variations of this product in different lengths and styles.... search the shop for etape

**Additional context**
basically two things to track, it is a little 2 foot deep well in many midwest basements. If you get heavy rain, the well fills up and it pumps out the water to a safe distance from the house to keep the basement from either flooding or leaking. Its nice to just know when the sump pump is running (the tracker can tell you when the number gets to a certain level). But also important to warn you if the water exceeds a certain level to let you know if your pump has failed (very common)
10:40
there are lots of expensive gadgets out there that track if your sump is failing, this would be a nice little solution. I would do an analog version, and a digital version (with the water sensor we already have). Can have digital version just track if the water gets to a certain level.

**Comment by brentru** [comment]
This issue is marked for [Hacktoberfest 2022](https://hacktoberfest.com/). If you are participating in Hacktoberfest and want to take on this issue, please first **fully read through** the guide for ["How to add a new component to Adafruit IO WipperSnapper"](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper).

For I2C Components to work, please note that you are required to add **both** an I2C component definition ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)) to this repository **and** an I2C component driver ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)) to [the WipperSnapper Firmware Repository](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/).

If you have any questions, comments, or concerns, please feel free to tag me in the comments here, or in your pull request for review. 

Happy Hackin'!

**Comment by brentru** [comment]
Addressed in https://github.com/adafruit/Wippersnapper_Components/pull/108

**Comment by brentru** [comment]
Resolved in https://github.com/adafruit/Wippersnapper_Components/pull/108
