### ISSUE TITLE
[REQ] Component Request: VL53L4CX ToF distance sensor

### ISSUE THREAD

**Issue by OdorDecoder** [adafruit/Wippersnapper_Components#76]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
VL53L4CX ToF distance sensor

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
[https://www.adafruit.com/product/5425]
Add any other context about the component request here.
I would like to use this with the QT PY ESP32 S2, with the STEMMA/QT connector, and in Arduino IDE it requires this code in the setup "Wire1.setPins(SDA1, SCL1);", also QT PY ESP32 S2 has no pull-up resistors.

**Comment by brentru** [comment]
This issue is marked for [Hacktoberfest 2022](https://hacktoberfest.com/). If you are participating in Hacktoberfest and want to take on this issue, please first **fully read through** the guide for ["How to add a new component to Adafruit IO WipperSnapper"](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper).

For I2C Components to work, please note that you are required to add **both** an I2C component definition ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)) to this repository **and** an I2C component driver ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)) to [the WipperSnapper Firmware Repository](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/).

If you have any questions, comments, or concerns, please feel free to tag me in the comments here, or in your pull request for review. 

Happy Hackin'!

**Comment by tyeth** [comment]
This has been added! Closed by #231
