### ISSUE TITLE
[REQ] Component Request: Adafruit NAU7802

### ISSUE THREAD

**Issue by ghost** [adafruit/Wippersnapper_Components#78]
What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?
Adafruit NAU7802 24-Bit ADC - STEMMA QT / Qwiic

What type of component is this (i.e.: Pin, I2C)?
I2C

Product URL or Datasheet
https://www.adafruit.com/product/4538

Additional context
The following features are nice to have from Adafruit.io page
1. Enter calibration coefficients
2. Select unit (kg/g/lb-oz)

**Comment by brentru** [comment]
This issue is marked for Hacktoberfest 2022. If you are participating in Hacktoberfest and want to take on this issue, please first **fully read through** the guide for ["How to add a new component to Adafruit IO WipperSnapper"](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper).

For I2C Components to work, please note that you are required to add **both** an I2C component definition ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)) to this repository **and** an I2C component driver ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)) to [the WipperSnapper Firmware Repository](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/).

If you have any questions, comments, or concerns, please feel free to tag me in the comments here, or in your pull request for review. 

Happy Hackin'!

**Comment by tyeth** [comment]
Closed by #225
